# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 05:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_details',
            name='billing_postal',
            field=models.IntegerField(verbose_name='Billing Postal Code'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_number',
            field=models.IntegerField(help_text='Put 8 digit Singapore Number', verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='shipping_details',
            name='shipping_postal',
            field=models.IntegerField(verbose_name='Shipping Postal Code'),
        ),
    ]
