# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-21 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20170809_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, help_text='Business Trading Name', max_length=75, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='company_reg_no',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Company Registration Number'),
        ),
    ]
