# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-21 05:20
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_auto_20170821_1320'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_type', models.CharField(choices=[('T1', 'Template 1: GST Excluded, Quantity Not Required, Total Not Required'), ('T2', 'Template 2: GST Included, Quantity Not Required, Total Not Required'), ('T3', 'Template 3: GST Excluded, Quantity Required, Total Shown'), ('T4', 'Template 4: GST Included, Quantity Required, Total Shown')], default='T1', max_length=2)),
                ('quote_subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Subtotal')),
                ('quote_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Total')),
                ('quote_gst', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='GST')),
                ('created_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Date of Creation')),
                ('confirmation_status', models.BooleanField(default=False, verbose_name='Confirmation Status')),
                ('billing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Billing_Details', verbose_name='Billing Address')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer', verbose_name='Customer Details')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Shipping_Details', verbose_name='Shipping Address')),
            ],
        ),
    ]
